
name: AFAIK

description: Main Plugin for the AFAIK Server

author: Patrick97
website: http://lavahayn.de

main: de.Lavahayn.Main.baseClass

version: 0.1-Blueberry

commands:
    hochzeit:
        description: Marries you to another player.
        aliases: [h]
        permission: marriage
        usage: /hochzeit Hilfe
    addNewRecipe:
        description: Adds a recipe to the server.
        aliases: [anr]
        permission: addNewRecipe
        usage: /addNewRecipe
    wipeAllRecipes:
        description: resets all server recipes.
        aliases: [war]
        permission: wipeAllRecipes
        usage: /wipeAllRecipes
permissions:
    marriage:
        default: false
        description: Grants a player the permission to marry another player
    addNewRecipe:
        default: false
        description: Grants a player the permission to add a new recipe
    wipeAllRecipes:
        default: false
        description: Grants a player the permission to add a new recipe
